### ISSUE TITLE
PR

### ISSUE THREAD

**Issue by quentinalbertone** [brightzheng100/kube4dev#2]
Hi, I like your readme 
(especially the one about kind) and I would like to propose a PR 
but I don't know how :sweat_smile:

**Comment by brightzheng100** [comment]
Thanks for your interest. @quentinalbertone 

You're lucky as I just compiled a super simple guide for this, check it out:
https://brightzheng100.github.io/post/2021/06/contributing-to-oss-projects-with-git-practices-part-1/

**Comment by quentinalbertone** [comment]
nice, I will do it this week-end
